classdef config
%configuration options for rbis. 
% 
% These are designed to help not crash Matlab by not overflowing memory in
% a call to SeDuMi or something similar. Modify them at your own risk.
    properties (Constant = true)
        % Maximum dimensions allowed by datahankel.
        MAX_DATAHANKEL_ROWS = 3000
        MAX_DATAHANKEL_COLS = 5000
    end
    
    methods
        function disp(x)
            fprintf([...
'  RBIS Configuration Parameters:\n'...
'  ------------------------------\n'...
'  These are default configuration parameters for RBIS. They are intended\n'...
'  to prevent Matlab from crashing when calling external solvers. Edit the\n'...
'  file "rbis.config.m" to change (at your own risk).\n\n'...
'    MAX_DATAHANKEL_ROWS (' num2str(x.MAX_DATAHANKEL_ROWS) ')\n'...
'      Maximum number of total rows allowed for data hankel matrices.\n'...
'\n'...
'    MAX_DATAHANKEL_COLS (' num2str(x.MAX_DATAHANKEL_COLS) ')\n'...
'      Maximum number of total columns allowed for data hankel matrices.\n'...
'\n'])
        end
    end
end

